name: CI/CD

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE_NAME: simple-chat-app
  DOCKER_HUB_USERNAME: sesiom6
  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
  SSH_USER: ${{ secrets.EC2_SSH_USER }}
  SSH_HOST: ${{ secrets.EC2_SSH_HOST }}
 # SSH_PORT: ${{ secrets.EC2_SSH_PORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
    - name: Build, tag, and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
    deploy:
      needs: build
      runs-on: ubuntu-latest
    
      steps:  
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          args: "-rlgoDzvc -i"
          env: |
            DOCKER_IMAGE_NAME=${{ env.DOCKER_IMAGE_NAME }}
          script: |
              ssh -i "${{ env.SSH_PRIVATE_KEY }}" "${{ env.SSH_USER }}@${{ env.SSH_HOST }}" << 'ENDSSH'
              sudo docker stop my-docker-container || true
              sudo docker rm my-docker-container || true
              sudo docker pull ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
              sudo docker run -d -p 80:3000 ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
              ENDSSH