name: CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: simple-chat-app
  DOCKER_HUB_USERNAME: sesiom6
  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
  SSH_USER: ${{ secrets.EC2_SSH_USER }}
  SSH_HOST: ${{ secrets.EC2_SSH_HOST }}
 # SSH_PORT: ${{ secrets.EC2_SSH_PORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
    - name: Build, tag, and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:  
     - name: Deploy to EC2
       uses: easingthemes/ssh-deploy@v2
       env:
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./"
          REMOTE_HOST: ${{ env.SSH_HOST }}
          REMOTE_USER: ${{ env.SSH_USER }}
          TARGET: "/home/ec2-user"
          SCRIPT_AFTER: |
            sudo su -
            sudo docker stop $(docker ps -q)
            sudo rmi -f $(docker images -q)
            sudo docker pull ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            sudo docker run -d -p 8080:3000 ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            echo $RSYNC_STDOUT